version: "3.9"
services:
  nats:
    container_name: plane-nats
    image: nats:latest
    command:
      "--jetstream ${NATS_FLAGS}"
    ports:
      - "127.0.0.1:4222:4222"
    networks:
      - plane