version: "3.9"
services:
  drone:
    container_name: plane-drone
    image: ghcr.io/drifting-in-space/plane-drone:latest
    volumes:
      - ..:/etc/plane:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      /etc/plane/drone.toml
    networks:
      - plane
  
  controller:
    container_name: plane-controller
    image: ghcr.io/drifting-in-space/plane-controller:latest
    volumes:
      - ..:/etc/plane:ro
    command:
      /etc/plane/controller.toml
    networks:
      - plane

  nats:
    container_name: plane-nats
    image: nats:latest
    command:
      "-DV --jetstream"
    ports:
      - "127.0.0.1:4222:4222"
    networks:
      - plane

  ip-api:
    container_name: plane-ip-api
    image: ghcr.io/drifting-in-space/ip-api:latest
    networks:
      - plane

  dnsmasq:
    container_name: plane-dnsmasq
    image: dnsmasq
    networks:
      plane:
        ipv4_address: 172.16.238.10
    build: ../dnsmasq
    volumes:
      - ../dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf


networks:
  plane:
    name: plane
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1


    
