[workspace]
resolver = "2"
members = [
    "plane/plane-tests",
    "plane/plane-dynamic",
    "plane",
    "plane/plane-tests/plane-test-macro",
]
default-members = [
    "plane",
    "plane/plane-tests"
]
