version: "3.9"
services:
  drone:
    container_name: plane-drone
    # build:
    #   context: .
    #   dockerfile: drone/Dockerfile
    image: ghcr.io/drifting-in-space/plane-drone:latest
    volumes:
      - ./sample-config:/etc/plane:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      /etc/plane/drone.toml
    networks:
      - plane

  controller:
    container_name: plane-controller
    # build:
    #   context: .
    #   dockerfile: controller/Dockerfile
    image: ghcr.io/drifting-in-space/plane-controller:latest
    volumes:
      - ./sample-config:/etc/plane:ro
    command:
      /etc/plane/controller.toml
    networks:
      - plane

  nats:
    container_name: plane-nats
    image: nats:latest
    command:
      "--jetstream"
    ports:
      - "127.0.0.1:4222:4222"
    networks:
      - plane

  ip-api:
    container_name: plane-ip-api
    image: ghcr.io/drifting-in-space/ip-api:latest
    networks:
      - plane

  firefox:
    container_name: plane-firefox
    build:
      context: sample-config
      dockerfile: firefox/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - plane

networks:
  plane:
    name: plane
