apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: spawner
build:
  local:
    push: false
  artifacts:
  - image: ghcr.io/drifting-in-space/spawner-controller
    context: crates/
    custom:
      buildCommand: ./build_container.sh spawner-controller
      dependencies:
        dockerfile:
          path: Dockerfile
  - image: ghcr.io/drifting-in-space/spawner-api
    context: crates/
    custom:
      buildCommand: ./build_container.sh spawner-api
      dependencies:
        dockerfile:
          path: Dockerfile
  - image: ghcr.io/drifting-in-space/spawner-sidecar
    context: crates/
    custom:
      buildCommand: ./build_container.sh spawner-sidecar
      dependencies:
        dockerfile:
          path: Dockerfile
  - image: ghcr.io/drifting-in-space/spawner-sweeper
    context: crates/
    custom:
      buildCommand: ./build_container.sh spawner-sweeper
      dependencies:
        dockerfile:
          path: Dockerfile
deploy:
  kubeContext: minikube
  kustomize:
    paths:
    - cluster
