version: "3.9"
services:
  drone:
    build:
      context: .
      dockerfile: drone/Dockerfile
    # image: ghcr.io/drifting-in-space/plane-drone:latest
    volumes:
      - ./:/etc/plane:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      /etc/plane/drone.toml

  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    # image: ghcr.io/drifting-in-space/plane-controller:latest
    volumes:
      - ./:/etc/plane:ro
    command:
      /etc/plane/controller.toml

  nats:
    image: nats:latest
    command:
      "--jetstream"
    ports:
      - "127.0.0.1:4222:4222"

  ip-api:
    image: ghcr.io/drifting-in-space/ip-api:latest

  firefox:
    build:
      dockerfile: firefox/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
