[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
bollard = "0.13.0"
dis-spawner = {path = "../core"}
dis-spawner-drone = {path = "../drone"}
tokio = { version = "1.20.1", features = ["macros"] }
tokio-stream = "0.1.9"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "ansi"] }
integration-test = { path = "./integration-test" }
rcgen = "0.9.3"
serde_json = "1.0.83"
reqwest = { version = "0.11.11", features=["native-tls"] }
openssl = "0.10.41"
tracing-appender = "0.2.2"
async-nats = "0.18.0"
