[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
bollard = "0.13.0"
dis-spawner = {path = "../core"}
tokio = { version = "1.20.1", features = ["macros"] }
tokio-stream = "0.1.9"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
integration-test = { path = "./integration-test" }
