[package]
name = "plane-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
plane-core = {path = "../core"}
clap = { version = "4.0.4", features = ["derive"] }
anyhow = "1.0.65"
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
async-nats = "0.20.0"
colored = "2.0.0"
tracing = "0.1.36"
