[package]
name = "plane-cli"
version = "0.3.1"
edition = "2021"
authors = ["Paul Butler <paul@driftingin.space>"]
homepage = "https://plane.dev"
description = "Session backend orchestrator for ambitious browser-based apps."
repository = "https://github.com/drifting-in-space/plane"
license = "MIT"
readme = "README.md"

[dependencies]
plane-core = {path = "../core", version="0.3.0"}
clap = { version = "4.0.4", features = ["derive"] }
anyhow = "1.0.65"
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
async-nats = "0.21.0"
colored = "2.0.0"
tracing = "0.1.36"
