[workspace]

members = [
    "api",
    "cli",
    "controller",
    "core",
    "sidecar",
    "sweeper",
    "tracing",
]

[patch.crates-io]
tracing-stackdriver = {git = "https://github.com/drifting-in-space/tracing-stackdriver.git"}