name: Build Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths-ignore: [ "/docs" ]

  pull_request:
    branches: [ "main" ]
    paths:
    # Unless the Dockerfile itself has changed, testing whether a build passes
    # on a PR doesn’t tell us much that faster CI/CD workflows don’t already.
    - '.github/workflows/build-image.yml'
    - 'docker/Dockerfile'

env:
  IMAGE_NAME: plane/plane

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Depot
        uses: depot/setup-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push Docker image
        id: build-and-push
        uses: depot/build-push-action@v1
        with:
          context: "."
          file: "docker/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != 'jamsocket/plane' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          buildx-fallback: true
          project: 58j0517pw2
