name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true
    - run: npm install
      working-directory: tests
    # The tests build, but they are likely to hit their timeout if the cache isn't warm.
    - name: Run tests
      run: cargo test --verbose
    - run: npm test
      working-directory: tests
