name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: rui314/setup-mold@v1
    - uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true
    - run: npm install
      working-directory: tests
    - run: npm test
      working-directory: tests
