name: Run Clippy (plane2-preview)

on:
  pull_request:
    branches: [ "plane2-preview" ]

jobs:
  check-rust-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
