name: Check Rust formatting

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-rust-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Check format
        run: cargo fmt -- --check
