name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true
    - name: Build test image
      run: docker build -t spawner-test-image:latest .
      with:
        working-directory: tests/test-image
    - name: Run tests
      run: cargo test --verbose
